### ISSUE TITLE
No longer works in iOS

### ISSUE THREAD

**Issue by markjerz** [waveform80/pistreaming#11]
Hi,

This no longer seems to work in iOS (I think since I upgraded to 10.) 

Any thoughts? I don't see any error messages client or server side so at a bit of a loss.

Thanks.

**Comment by waveform80** [comment]
I'm afraid I've got no Apple products so this isn't something I can test. I'm getting a fair bit of e-mail regarding this, but all I can say at the moment is that this *might* be something to do with Apple doing something weird with websockets. Until I can get some concrete information though, I'm afraid I'll just have to mark pistreaming as "doesn't work with modern iOS devices" (oh well, bang goes the claim that it works on nearly everything ... still, goes to show just how bloody complex getting something to work on nearly all browsers actually is!)

**Comment by WayneKeenan** [comment]
I was getting the following error in Safari on iOS and Mac

```WebSocket connection to 'ws://192.168.1.100:8084/' failed: Invalid HTTP version string: HTTP/1.0```

I have a fix incoming...

**Comment by wujunze** [comment]
When do you combine this feature?  @waveform80

**Comment by waveform80** [comment]
I'd forgotten about this, but there's some relevant discussion in #21: looks like I was waiting for someone to confirm a simpler fix would work on iOS. Given it's hung around though I'll just commit the simpler fix as it doesn't seem to affect anything on Linux/Windows/Android.
