### ISSUE TITLE
No module name http.server?

### ISSUE THREAD

**Issue by creepandpeep** [waveform80/pistreaming#14]
Hi,

Followed instructions, but upon running server.py:

```
~/pistreaming $ ./server.py
Traceback (most recent call last):
  File "./server.py", line 12, in <module>
    from http.server import HTTPServer, BaseHTTPRequestHandler
ImportError: No module named http.server
```

I'm sure it's something obvious, but I'm a beginner. . . .could you help me out?

**Comment by magicmad** [comment]
You need to use python 3, since python 2.7 does not have the HTTPServer.
starting it with "python3 server.py" should work.

**Comment by creepandpeep** [comment]
wow - always the simple things :) works perfectly - stream is looking ace as well - thanks for the quick help !

**Comment by SufyanParkar** [comment]
> You need to use python 3, since python 2.7 does not have the HTTPServer.
> starting it with "python3 server.py" should work.

Not working for me

**Comment by sargentpanda** [comment]
yeah nothing is working for me

**Comment by DarioDiGulio** [comment]
If your package named http, change this name. Working for me

**Comment by Chdlopezes** [comment]
> If your package named http, change this name. Working for me

Yeah, I had this problem even with Python 3, so I change the name of my module, which was called "http". After the change, it works. Thank you!

**Comment by zhc341272** [comment]
来信已收到，谢谢，吼吼！O(∩_∩)O~
