### ISSUE TITLE
Code of Capture image in browser using Web Socket 

### ISSUE THREAD

**Issue by rajshah4488** [waveform80/pistreaming#23]
Hello Sir,
AM working on this project. But, in additional I have one requirement regarding capture image from browser. Can you help me out how it can be possible to capture image from browser with PiCamera and using web Socket.
Its Urgent..

Waiting for positive response..

Thankyou

**Comment by AuspeXeu** [comment]
This is more a question for stackoverflow.com

**Comment by waveform80** [comment]
Yup, definitely a question for SO - this isn't anything to do with the pistreaming project specifically so I'm closing it for now.
