### ISSUE TITLE
How to change the resolution of video?

### ISSUE THREAD

**Issue by EpochT** [waveform80/pistreaming#24]
I simply changed the resolution in server.py but I met the "Broken pipe [Error 32]" error, So I wonder if I can change the resolution higher, like 720p, and how?

**Comment by waveform80** [comment]
You can change the resolution, but be aware of the issue mentioned in #18 (the resolution selected must be a multiple of 32x16). The broken pipe error may be related to #13 for which I've just committed a fix. I'll close this ticket for now, but do feel free to re-open if you're still experiencing a problem!
